#!/bin/bash

python main.py --dataset beauty train --accelerator gpu --devices 1 --val_epochs 1 --epochs 20 --batch_size 50 --batch_accum 1 --num_loader_workers 3 --partial_save CTGR --train_style dgsr_softmax --loss_fn ce --dropout 0 --add_self_loops --convolution GAT  neighbour --newsampler --n_max_trans 50 --m_order 1 --sample_all
python main.py --dataset beauty train --accelerator gpu --devices 1 --val_epochs 1 --epochs 20 --batch_size 50 --batch_accum 1 --num_loader_workers 3 --partial_save CTGR --train_style dgsr_softmax --loss_fn ce --dropout 0 --add_self_loops --convolution GAT --edge_attr positional neighbour --newsampler --n_max_trans 50 --m_order 1 --sample_all
#python main.py --dataset beauty train --accelerator gpu --devices 1 --val_epochs 1 --epochs 20 --batch_size 50 --batch_accum 1 --num_loader_workers 3 --partial_save CTGR --train_style dgsr_softmax --loss_fn ce --dropout 0 --add_self_loops --convolution GAT --edge_attr continuous neighbour --newsampler --n_max_trans 50 --m_order 1 --sample_all
python main.py --dataset beauty train --accelerator gpu --devices 1 --val_epochs 1 --epochs 20 --batch_size 50 --batch_accum 1 --num_loader_workers 3 --partial_save CTGR --train_style dgsr_softmax --loss_fn ce --dropout 0 --add_self_loops --convolution GATv2  neighbour --newsampler --n_max_trans 50 --m_order 1 --sample_all
python main.py --dataset beauty train --accelerator gpu --devices 1 --val_epochs 1 --epochs 20 --batch_size 50 --batch_accum 1 --num_loader_workers 3 --partial_save CTGR --train_style dgsr_softmax --loss_fn ce --dropout 0 --add_self_loops --convolution GATv2 --edge_attr positional  neighbour --newsampler --n_max_trans 50 --m_order 1 --sample_all
#python main.py --dataset beauty train --accelerator gpu --devices 1 --val_epochs 1 --epochs 20 --batch_size 50 --batch_accum 1 --num_loader_workers 3 --partial_save CTGR --train_style dgsr_softmax --loss_fn ce --dropout 0 --add_self_loops --convolution GATv2 --edge_attr continuous  neighbour --newsampler --n_max_trans 50 --m_order 1 --sample_all


# Also try: try more heads